#!/bin/bash

echo "Build hook running..."

IMAGE_VERSION=`cat VERSION`

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg VERSION=$IMAGE_VERSION \
             -t $IMAGE_NAME .

